import { shelfAction } from './helpers/shelf';
import { openViewingTools, closeViewingTools, openFrame, captureCanvas } from "./helpers/viewing";
import { test, expect } from '@playwright/test';
import { PNG } from 'pngjs';
import fs from 'node:fs/promises';

test('crop drag follows the image and persists through save, reload, cancellation and rotation',async({page})=>{
  await page.goto('/guest?mode=inspect&reduced_motion=true');
  await page.getByRole('button',{name:'Film Shelf',exact:true}).click();
  await shelfAction(page, 'New roll');
  const png=new PNG({width:900,height:300});
  for(let y=0;y<300;y++)for(let x=0;x<900;x++)png.data.set(x<300?[220,35,35,255]:x<600?[35,220,35,255]:[35,35,220,255],(y*900+x)*4);
  await page.getByLabel('Choose photographs').setInputFiles([{name:'composition.png',mimeType:'image/png',buffer:PNG.sync.write(png)}]);
  await page.getByRole('button',{name:'Continue to roll details',exact:true}).click();
  await page.getByLabel('Roll name',{exact:true}).fill('Recompose');
  await page.getByRole('radio',{name:'120',exact:true}).check();
  await page.getByLabel('Film format',{exact:true}).selectOption('66');
  await page.getByRole('button',{name:'Review photographs',exact:true}).click();
  const surface=page.getByLabel('Drag photograph to recompose');
  const bounds=(await surface.boundingBox())!;
  await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);
  await page.mouse.down();await page.mouse.move(bounds.x+bounds.width,bounds.y+bounds.height/2,{steps:8});await page.mouse.up();
  await expect(page.getByLabel('Horizontal crop position')).toHaveValue('-1');
  await page.getByRole('button',{name:'Show final crop',exact:true}).click();
  const isRed=(image:PNG)=>{const i=(Math.floor(image.height/2)*image.width+Math.floor(image.width/2))*4;expect(image.data[i]).toBeGreaterThan(image.data[i+1]+80);};
  isRed(PNG.sync.read(await surface.screenshot()));
  const output=`${process.env.M14_CANDIDATE_DIR || 'artifacts/m14-candidates'}/recompose`;await fs.mkdir(output,{recursive:true});
  await page.getByRole('region',{name:'Crop inspector'}).screenshot({path:`${output}/review.png`});
  const save=async()=>{await page.getByRole('button',{name:'Save and open',exact:true}).click();await expect(page.locator('main')).toHaveAttribute('data-assets-ready','true');await expect(page.locator('main')).toHaveAttribute('data-is-transitioning','false');};
  await save();
  await openFrame(page,1);
  await expect(page.locator('main')).toHaveAttribute('data-is-transitioning','false');
  await openViewingTools(page);await page.getByRole('button',{name:'Switch to Positive',exact:true}).click();await page.waitForTimeout(700);
  isRed(PNG.sync.read(await captureCanvas(page, {path:`${output}/film.png`})));
  await page.reload();await expect(page.locator('main')).toHaveAttribute('data-assets-ready','true');await expect(page.locator('main')).toHaveAttribute('data-is-transitioning','false');await page.waitForTimeout(700);
  isRed(PNG.sync.read(await captureCanvas(page)));
  const edit=async()=>{await closeViewingTools(page);if(await page.locator('main').getAttribute('data-focus-mode')==='true'){await page.getByRole('button',{name:'← Overview',exact:true}).click();await expect(page.locator('main')).toHaveAttribute('data-is-transitioning','false');}await page.getByRole('button',{name:'Film Shelf',exact:true}).click();await page.getByRole('button',{name:'Show saved roll Recompose',exact:true}).click();await page.getByRole('button',{name:'Edit Recompose',exact:true}).click();};
  await edit();await expect(page.getByLabel('Horizontal crop position')).toHaveValue('-1');
  await page.getByRole('button',{name:'Center crop',exact:true}).click();await expect(page.getByLabel('Horizontal crop position')).toHaveValue('0');
  await page.getByRole('button',{name:'Cancel edits',exact:true}).click();
  await edit();await expect(page.getByLabel('Horizontal crop position')).toHaveValue('-1');
  await page.getByRole('button',{name:'Rotate frame 1',exact:true}).click();await expect(page.getByLabel('Vertical crop position')).toHaveValue('-1');
  await page.getByRole('button',{name:'Show final crop',exact:true}).click();isRed(PNG.sync.read(await surface.screenshot()));
  await save();await openFrame(page,1);await page.waitForTimeout(700);isRed(PNG.sync.read(await captureCanvas(page)));
});
