import { IMPORT_LIMITS } from '../../src/storage/importPhotos';
import { openViewingTools, openFrame, captureCanvas } from "./helpers/viewing";
import {test,expect,Page} from '@playwright/test';
import {PNG} from 'pngjs';
import fs from 'node:fs/promises';
const OUT=process.env.M14_CANDIDATE_DIR || 'artifacts/m14-candidates';
function chart(name:string,seed=0,width=600,height=400){const p=new PNG({width,height});for(let y=0;y<height;y++)for(let x=0;x<width;x++){const i=(y*width+x)*4;const v=x%6<3?230:25;p.data[i]=v;p.data[i+1]=y<height/2?40+seed%100:180;p.data[i+2]=60+(seed*19)%150;p.data[i+3]=255;}return {name,mimeType:'image/png',buffer:PNG.sync.write(p)};}
async function begin(page:Page){await page.goto('/?mode=inspect&example=1');await page.getByRole('button',{name:'Rolls',exact:true}).click();await page.getByRole('button',{name:'New roll',exact:true}).click();}
async function add(page:Page,files:ReturnType<typeof chart>[]){await page.getByLabel('Choose photographs',{exact:true}).setInputFiles(files);await expect(page.getByText(`Processed ${files.length} / ${files.length}`,{exact:true})).toBeVisible({timeout:120000});}
async function ready(page:Page){await expect(page.locator('main')).toHaveAttribute('data-is-transitioning','false',{timeout:30000});await expect(page.locator('main')).toHaveAttribute('data-assets-ready','true',{timeout:60000});}
async function details(page:Page,name:string){await page.getByRole('button',{name:'Continue to roll details'}).click();await page.getByLabel('Roll name',{exact:true}).fill(name);}
async function review(page:Page){await page.getByRole('button',{name:'Review photographs',exact:true}).click();}
async function save(page:Page){await page.getByRole('button',{name:'Save and open',exact:true}).click();await expect(page.getByRole('dialog')).not.toBeVisible();await ready(page);}
async function capture(page:Page,name:string){await fs.mkdir(OUT,{recursive:true});await page.screenshot({path:`${OUT}/${name}.png`});}
async function bundle(page:Page){return page.evaluate(()=>new Promise<any>(resolve=>{const q=indexedDB.open('darkroom-rolls');q.onsuccess=()=>{const db=q.result,tx=db.transaction(['rolls','frames','blobs']),r=tx.objectStore('rolls').getAll(),f=tx.objectStore('frames').getAll(),b=tx.objectStore('blobs').count();tx.oncomplete=()=>{resolve({rolls:r.result,frames:f.result,blobs:b.result});db.close();};};}));}
test('M14 staged import appends atomically and crop review persists only on save',async({page})=>{
  await begin(page);await capture(page,'01-photographs-empty');await add(page,[chart('scan2.png'),chart('scan10.png',1)]);await details(page,'A long summer — portraits, streets and quiet afternoons');await page.getByRole('radio',{name:'120',exact:true}).check();await page.getByLabel('Film format',{exact:true}).selectOption('67');await capture(page,'02-roll-details');await review(page);await page.getByRole('button',{name:'Select frame 2',exact:true}).click();await page.getByLabel('Rotate frame 2',{exact:true}).click();await page.getByRole('button',{name:'Cover',exact:true}).click();await capture(page,'03-crop-review');
  await page.getByRole('button',{name:'Photographs',exact:true}).click();await add(page,[chart('scan1.png',2),chart('duplicate.png')]);await page.getByRole('button',{name:'Roll details',exact:true}).click();await expect(page.getByLabel('Roll name',{exact:true})).toHaveValue('A long summer — portraits, streets and quiet afternoons');await review(page);
  const names=await page.locator('.draft-photos li').allTextContents();expect(names[0]).toContain('scan2.png');expect(names[1]).toContain('scan10.png');expect(names[2]).toContain('duplicate.png');expect(names[3]).toContain('scan1.png');
  await expect(page.getByRole('button',{name:'Save and open',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Select frame 3',exact:true}).click();await page.getByLabel('Keep this duplicate content').check();await page.getByRole('button',{name:'Select frame 2',exact:true}).click();
  const gate=await page.getByTestId('crop-gate').evaluate(el=>({width:el.getBoundingClientRect().width,height:el.getBoundingClientRect().height}));expect(gate.width/gate.height).toBeCloseTo(68.5/56,2);
  await page.getByRole('button',{name:'Show final crop'}).click();await capture(page,'04-final-crop');await save(page);let b=await bundle(page);expect(b.frames.find((f:any)=>f.filename==='scan10.png').rotation).toBe(90);expect(b.rolls[0].frameIds).toHaveLength(4);const id=b.rolls[0].id;
  await page.getByRole('button',{name:'Rolls',exact:true}).click();await capture(page,'05-library');const actions=page.getByRole('button',{name:'Actions for A long summer — portraits, streets and quiet afternoons',exact:true});await actions.click();await page.keyboard.press('Escape');await expect(actions).toBeFocused();await actions.click();await page.getByRole('menuitem',{name:/^Edit /}).click();await review(page);await page.getByRole('button',{name:'Select frame 2',exact:true}).click();await page.getByLabel('Rotate frame 2',{exact:true}).click();await page.getByRole('button',{name:'Cancel edits'}).click();b=await bundle(page);expect(b.frames.find((f:any)=>f.filename==='scan10.png').rotation).toBe(90);
  await actions.click();await page.getByRole('menuitem',{name:/^Edit /}).click();await review(page);await page.getByRole('button',{name:'Select frame 4',exact:true}).click();await page.getByRole('button',{name:'Remove scan1.png',exact:true}).click();await save(page);b=await bundle(page);expect(b.frames).toHaveLength(3);expect(b.blobs).toBe(9);await page.reload();await expect(page.locator('main')).toHaveAttribute('data-roll-id',id);await ready(page);
});
test('M14 latest destination wins, adjacent textures stay resident, focus preserves framing and memory stays bounded',async({page})=>{
  await begin(page);await add(page,Array.from({length:24},(_,i)=>chart(`scan${i+1}.png`,i,2100,2100)));await details(page,'Navigation and residency');await review(page);await save(page);
  await page.getByRole('button',{name:'Focus frame 1',exact:true}).click();await expect(page.locator('main')).toHaveAttribute('data-inspection-level','frame');await page.getByRole('button',{name:'Next',exact:true}).click();await ready(page);await expect(page.locator('main')).toHaveAttribute('data-selected-frame','2');await page.getByRole('button',{name:'← Overview',exact:true}).click();await ready(page);
  await openFrame(page,6);await ready(page);const canvas=page.locator('canvas');const ids=JSON.parse((await canvas.getAttribute('data-texture-ids'))!);
  await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');await expect(page.locator('main')).toHaveAttribute('data-selected-frame','9');await ready(page);const after=JSON.parse((await canvas.getAttribute('data-texture-ids'))!);expect(after[5]).toBe(ids[5]);expect(after[6]).toBe(ids[6]);
  const camera=await canvas.getAttribute('data-camera-position');await expect(page.getByRole('button',{name:'← Overview',exact:true})).toBeVisible();await expect(page.getByRole('group',{name:'Frame map'})).not.toBeVisible();await capture(page,'06-focus');await page.getByRole('button',{name:'← Overview',exact:true}).click();await ready(page);await openFrame(page,9);expect(await canvas.getAttribute('data-camera-position')).toBe(camera);
  for(const n of [24,1,18,7,24,1]){await openFrame(page,n);await ready(page);expect(Number(await canvas.getAttribute('data-texture-bytes'))).toBeLessThanOrEqual(192*1024*1024);}
  await fs.writeFile(`${OUT}/cache-memory.json`,JSON.stringify({bytes:Number(await canvas.getAttribute('data-texture-bytes')),textures:Number(await canvas.getAttribute('data-texture-count')),frame6ResidentAcrossBoundary:true,frame7ResidentAcrossBoundary:true},null,2));
});
test('M14 higher resolution detail is visible and retains the viewing texture on failure',async({page})=>{
  await begin(page);await add(page,[chart('3072-resolution-chart.png',0,3072,2048)]);await details(page,'Resolution chart');await page.getByRole('dialog').getByLabel('Film stock',{exact:true}).selectOption('ektachrome-e100');await review(page);await save(page);await openFrame(page,1);await ready(page);
  const canvas=page.locator('canvas');await expect(canvas).toHaveAttribute('data-texture-edge','2048');await openViewingTools(page);await page.getByTestId('loupe-toggle').click();await page.getByTestId('mag-btn-8x').click();await expect(canvas).toHaveAttribute('data-texture-edge','3072',{timeout:30000});await expect(page.getByText('Detail ready · 3072px',{exact:true})).toBeVisible();await capture(page,'07-detail-3072');expect(Number(await canvas.getAttribute('data-texture-bytes'))).toBeLessThanOrEqual(192*1024*1024);
  // Compare real rendered macro samples with/without the original decode on reload.
  await page.waitForTimeout(500);const detailed=PNG.sync.read(await captureCanvas(page));
  const rollId=(await page.locator('main').getAttribute('data-roll-id'))!;
  // Install before startup: the restored camera can request detail during reload.
  await page.addInitScript(()=>{(window as any).__restoreDetail=window.createImageBitmap;window.createImageBitmap=async()=>{throw new Error('Deliberate detail decode failure');};});
  await page.reload();
  // The example scene may settle before the saved roll opens and resets the loupe.
  await expect(page.locator('main')).toHaveAttribute('data-roll-id',rollId);await ready(page);
  await openViewingTools(page);await page.getByTestId('loupe-toggle').click();await expect(page.locator('main')).toHaveAttribute('data-loupe-state','activated');await page.getByTestId('mag-btn-8x').click();await expect(page.getByText('Detail unavailable. Viewing image retained.',{exact:false})).toBeVisible({timeout:30000});await expect(canvas).toHaveAttribute('data-texture-edge','2048');await expect(page.getByRole('button',{name:'Retry detail'})).toBeVisible();const fallback=PNG.sync.read(await captureCanvas(page));
  const contrast=(p:PNG)=>{let sum=0,n=0;for(let y=Math.floor(p.height/2)-25;y<Math.floor(p.height/2)+25;y++)for(let x=Math.floor(p.width/2)-25;x<Math.floor(p.width/2)+25;x++){const i=(y*p.width+x)*4;sum+=Math.abs(p.data[i]-p.data[i+4]);n++;}return sum/n;};
  await fs.writeFile(`${OUT}/detail-comparison.json`,JSON.stringify({source:'Generated 3072×2048 PNG, 3px alternating bars; original retained in IndexedDB',detailEdge:3072,viewingEdge:2048,detailedContrast:contrast(detailed),fallbackContrast:contrast(fallback)},null,2));
  expect(contrast(detailed)).toBeGreaterThan(contrast(fallback)*1.03);
  await page.evaluate(()=>{window.createImageBitmap=(window as any).__restoreDetail;});await page.getByRole('button',{name:'Retry detail'}).click();await expect(canvas).toHaveAttribute('data-texture-edge','3072',{timeout:30000});
});
test('M14 rejected and cancelled append keep the existing draft intact',async({page})=>{
  await begin(page);await add(page,[chart('first.png'),chart('second.png',1)]);await details(page,'Keep this draft');await review(page);await page.getByRole('button',{name:'Select frame 2',exact:true}).click();await page.getByLabel('Rotate frame 2',{exact:true}).click();await page.getByRole('button',{name:'Photographs',exact:true}).click();
  await page.getByLabel('Choose photographs',{exact:true}).setInputFiles(Array.from({length:IMPORT_LIMITS.files-1},(_,i)=>chart(`too-many-${i}.png`,i,30,20)));await expect(page.getByRole('alert')).toContainText(String(IMPORT_LIMITS.files));await expect(page.getByText('2 photographs selected',{exact:false})).toBeVisible();
  await page.evaluate(()=>{const decode=window.createImageBitmap;window.createImageBitmap=(...args:any[])=>new Promise((resolve,reject)=>setTimeout(()=>Reflect.apply(decode,window,args).then(resolve,reject),500));});
  await page.getByLabel('Choose photographs',{exact:true}).setInputFiles(Array.from({length:10},(_,i)=>chart(`cancel-${i}.png`,i,100,80)));await page.getByRole('button',{name:'Cancel processing',exact:true}).first().click();await expect(page.getByText('Processing cancelled. Your earlier photographs are retained.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Roll details',exact:true}).click();await expect(page.getByLabel('Roll name',{exact:true})).toHaveValue('Keep this draft');await review(page);await expect(page.locator('.draft-photos li')).toHaveCount(2);await save(page);const b=await bundle(page);expect(b.frames.find((f:any)=>f.filename==='second.png').rotation).toBe(90);expect(b.blobs).toBe(6);
});
