import { expectShelfSummary, shelfAction, ready, focusShelf, showRoll, openRoll, add } from './helpers/shelf';
import { test, expect } from '@playwright/test';
import fs from 'node:fs/promises';
const OUT = process.env.M18_REVIEW_DIR || 'artifacts/m18-candidates';

test('M18 shelf replaces the archive, with the five-photo example in slot 01 and no hover frame', async ({page}, info) => {
  await page.goto('/guest?mode=room&reduced_motion=true'); await ready(page);
  await expect(page.locator('[data-shelf-slot="0"]')).toHaveAttribute('data-owned','true');
  await expect(page.locator('[data-owned="false"]')).toHaveCount(15);
  await expect(page.getByRole('button',{name:'Open built-in example'})).toHaveCount(0);
  const cabinet = page.getByRole('button',{name:'View film shelf',exact:true});
  await cabinet.hover();
  await expect(cabinet).toHaveCSS('border-top-color','rgba(0, 0, 0, 0)');
  await expect(cabinet).toHaveCSS('box-shadow','none');
  await fs.mkdir(OUT,{recursive:true});
  await page.screenshot({path:`${OUT}/${info.project.name}-room-no-hover-frame.png`});
  await cabinet.click(); await ready(page);
  let card = await showRoll(page,'Roll 01');
  await expect(card).toContainText('5 photographs');
  await expect(card.getByRole('img')).toBeVisible();
  await page.screenshot({path:`${OUT}/${info.project.name}-shelf-library.png`});
  await card.getByRole('button',{name:'Edit Roll 01',exact:true}).click();
  await page.getByLabel('Roll name',{exact:true}).fill('My example');
  await page.getByRole('button',{name:'Save and open',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible(); await ready(page);
  await expect(page.locator('main')).toHaveAttribute('data-roll-id','roll-01');
  await focusShelf(page);
  await expect(page.getByRole('heading',{name:'Your rolls',exact:true})).toHaveCount(0);
  card = await showRoll(page,'My example');
  await card.getByRole('button',{name:'Delete My example',exact:true}).click();
  await expect(page.locator('[data-owned="true"]')).toHaveCount(0);
  await expect(page.locator('main')).toHaveAttribute('data-table-roll-available','false');
  await expectShelfSummary(page, '0 saved rolls');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await expect(page.locator('[data-shelf-slot="0"]')).toHaveAttribute('data-owned','true');
  await showRoll(page,'My example'); await page.getByRole('button',{name:'Delete My example',exact:true}).click();
  await expect(page.locator('[data-owned="true"]')).toHaveCount(0);
  await page.reload(); await ready(page); await focusShelf(page);
  await expect(page.locator('[data-owned="true"]')).toHaveCount(0);
  await expect(page.locator('main')).toHaveAttribute('data-table-roll-available','false');
  await shelfAction(page, 'Trash (1)');
  card = await showRoll(page,'My example');
  await expect(card.getByRole('button',{name:'Open on light table'})).toHaveCount(0);
  await card.getByRole('button',{name:'Restore My example',exact:true}).click();
  await shelfAction(page, 'Saved rolls');
  await openRoll(page,'My example');
  await expect(page.locator('main')).toHaveAttribute('data-table-roll-available','true');
  await expect(page.locator('main')).toHaveAttribute('data-roll-id','roll-01');
});

test('M18 new rolls and cancelled drafts return to the shelf', async ({page}) => {
  await page.goto('/guest?mode=inspect&reduced_motion=true'); await ready(page); await focusShelf(page);
  await shelfAction(page, 'New roll');
  await page.getByRole('button',{name:'Cancel draft',exact:true}).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.locator('main')).toHaveAttribute('data-shelf-focused','true');
  await expect(page.locator('[data-owned="true"]')).toHaveCount(1);
  await add(page,'Shelf addition','ektar-100','66');
  await expect(page.locator('[data-shelf-slot="1"]')).toHaveAttribute('data-packaging','ektar-100-120');
  const card = await showRoll(page,'Shelf addition');
  await expect(card).toContainText('1 photograph');
  await expect(card).toContainText('120 · 6×6');
  await card.getByRole('button',{name:'Edit Shelf addition',exact:true}).click();
  await page.getByLabel('Roll name',{exact:true}).fill('Discard this edit');
  await page.getByRole('button',{name:'Cancel edits',exact:true}).click();
  await showRoll(page,'Shelf addition');
  await page.getByRole('button',{name:'Delete Shelf addition',exact:true}).click();
  await expect(page.locator('[data-shelf-slot="1"]')).toHaveAttribute('data-owned','false');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await openRoll(page,'Shelf addition');
  await expect(page.locator('main')).toHaveAttribute('data-film-format','66');
});
