import { test, expect } from '@playwright/test';
import { ready } from './helpers/shelf';

test('guest menu remembers Desktop and returns to automatic layout without losing the roll', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/guest?mode=room&reduced_motion=true'); await ready(page);
  const app = page.locator('main'), menuButton = page.getByRole('button', { name: 'More options', exact: true });
  const rollId = await app.getAttribute('data-roll-id');
  const headerStyle = () => page.locator('.mobile-header').evaluate(node => {
    const style = getComputedStyle(node), button = getComputedStyle(node.querySelector('button')!);
    return { background: style.backgroundColor, border: style.borderBottomColor, buttonBackground: button.backgroundColor, buttonFont: button.fontSize, buttonRadius: button.borderRadius };
  });
  const automaticStyle = await headerStyle();
  await expect(app).toHaveClass(/mobile-layout/);
  await expect(menuButton).toHaveText('…');
  await menuButton.click();
  const menu = page.getByRole('menu', { name: 'More options', exact: true });
  await expect(menu.getByRole('menuitem', { name: 'Admin Login' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: /Create Your Own/ })).toHaveCount(0);
  await expect(menu.getByRole('menuitemradio', { name: 'Auto', exact: true })).toHaveAttribute('aria-checked', 'true');
  await page.screenshot({ path: info.outputPath('guest-auto-menu.png') });
  await page.keyboard.press('ArrowDown');
  await expect(menu.getByRole('menuitemradio', { name: 'Desktop', exact: true })).toBeFocused();
  await page.keyboard.press('Enter');
  await expect(app).not.toHaveClass(/mobile-layout/);
  expect(await headerStyle()).toEqual(automaticStyle);
  await expect(page.locator('.controls-footer, .room-nav-hint')).toHaveCount(0);
  await expect(menu).toHaveCount(0);
  await expect(menuButton).toBeFocused();
  await expect(app).toHaveAttribute('data-roll-id', rollId!);
  const bounds = (await menuButton.boundingBox())!;
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390);
  await page.reload(); await ready(page);
  await expect(app).not.toHaveClass(/mobile-layout/);
  await menuButton.click();
  await expect(menu.getByRole('menuitemradio', { name: 'Desktop', exact: true })).toHaveAttribute('aria-checked', 'true');
  const menuBounds = (await menu.boundingBox())!;
  expect(menuBounds.x).toBeGreaterThanOrEqual(0);
  expect(menuBounds.x + menuBounds.width).toBeLessThanOrEqual(390);
  await page.screenshot({ path: info.outputPath('desktop-request-on-phone.png') });
  await menu.getByRole('menuitemradio', { name: 'Auto', exact: true }).click();
  await expect(app).toHaveClass(/mobile-layout/);
  await page.setViewportSize({ width: 1280, height: 900 });
  const automaticMobile = await page.evaluate(() => matchMedia('(max-width: 1000px), (any-pointer: coarse)').matches);
  if (automaticMobile) await expect(app).toHaveClass(/mobile-layout/);
  else await expect(app).not.toHaveClass(/mobile-layout/);
  await page.reload(); await ready(page);
  await menuButton.click();
  await expect(menu.getByRole('menuitemradio', { name: 'Auto', exact: true })).toHaveAttribute('aria-checked', 'true');
  await page.keyboard.press('Escape');
  await expect(menuButton).toBeFocused();
});

test('desktop room tools remain available and film navigation has no bottom hint', async ({ page }, info) => {
  await page.goto('/guest?mode=room&reduced_motion=true'); await ready(page);
  await page.getByRole('button', { name: 'More options', exact: true }).click();
  await page.getByRole('menuitemradio', { name: 'Desktop', exact: true }).click();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  const panel = page.getByRole('dialog', { name: 'Viewing tools', exact: true });
  await expect(panel.getByRole('slider', { name: 'Room brightness', exact: true })).toBeVisible();
  await panel.getByRole('slider', { name: 'Room brightness', exact: true }).fill('0.6');
  await expect(page.locator('main')).toHaveAttribute('data-room-brightness', '0.6');
  await panel.getByRole('button', { name: 'Face table', exact: true }).click();
  await expect(panel).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('shared-desktop-header.png') });
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByTestId('approach-table-btn').click(); await ready(page);
  await expect(page.locator('main')).toHaveAttribute('data-room-mode', 'inspect');
  await expect(page.locator('.table-caption')).not.toBeVisible();
  await expect(page.getByRole('navigation', { name: 'Overview navigation', exact: true })).toHaveCount(0);
  await page.screenshot({ path: info.outputPath('desktop-film-without-hint.png') });
});

test('owner menu retains login and layout controls in the camera cabinet', async ({ page }, info) => {
  await page.goto('/?mode=room&reduced_motion=true'); await ready(page);
  const trigger = page.getByRole('button', { name: 'More options', exact: true });
  await trigger.click();
  await expect(page.getByRole('menuitem', { name: 'Admin Login', exact: true })).toBeVisible();
  await expect(page.getByRole('menuitemradio', { name: 'Auto', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: 'Cameras', exact: true }).click(); await ready(page);
  await trigger.click();
  await page.getByRole('menuitemradio', { name: 'Desktop', exact: true }).click();
  await expect(page.locator('main')).not.toHaveClass(/mobile-layout/);
  await expect(trigger).toBeVisible();
  await trigger.click();
  await expect(page.getByRole('menuitemradio', { name: 'Desktop', exact: true })).toHaveAttribute('aria-checked', 'true');
  await page.screenshot({ path: info.outputPath('cabinet-layout-menu.png') });
});
