"""Local taking-lens/shutter/focus-band inscriptions on the existing scan mesh.

Import-safe Blender module. Textures are generated by prepare_lower_front.py in
standalone remote Python. Only shallow shutter-letter relief may be leveled;
the glass, bezel, controls, original UV layers and all other geometry are retained.
"""
from pathlib import Path
import hashlib
import json

import bpy
import numpy as np
from front_inscription_normals import inscription_normals


_UV_NAME = 'Front inscription strips'
_PREFIX = 'Autocord lower front | '
# Independent front controls, measured in the existing orthographic closeups.
_CONTROL_DISKS = ((.118, .420, .025), (-.143, .269, .025),
                  (.182, .350, .016), (-.160, .205, .034),
                  (.184, .205, .034), (-.188, .114, .027))


def _digest(array):
    return hashlib.sha256(array.tobytes()).hexdigest()


def _uv_digests(mesh):
    digests = {}
    data = np.empty(len(mesh.loops)*2, np.float32)
    for layer in mesh.uv_layers:
        layer.data.foreach_get('uv', data)
        digests[layer.name] = _digest(data)
    return digests


def _image(reference_dir, filename, data=False):
    path = reference_dir/filename
    if not path.is_file():
        raise FileNotFoundError(path)
    image = bpy.data.images.load(str(path), check_existing=True)
    image.colorspace_settings.name = 'Non-Color' if data else 'sRGB'
    image.pack()
    return image


def _material(reference_dir, name, maps, uv_name):
    material = bpy.data.materials.new(_PREFIX+name)
    material.use_nodes = True
    material.diffuse_color = (.025, .025, .022, 1) if name != 'shutter' else (.43, .42, .39, 1)
    nodes, links = material.node_tree.nodes, material.node_tree.links
    bsdf = nodes.get('Principled BSDF')
    bsdf.inputs['Metallic'].default_value = 0.
    bsdf.inputs['Roughness'].default_value = .35
    uv = nodes.new('ShaderNodeUVMap')
    uv.uv_map = uv_name
    color = nodes.new('ShaderNodeTexImage')
    color.name = 'Restored inscription base color'
    color.image = _image(reference_dir, maps['basecolor'])
    color.interpolation = 'Linear'
    color.extension = 'EXTEND'
    packed = nodes.new('ShaderNodeTexImage')
    packed.name = 'Packed metallic roughness'
    packed.image = _image(reference_dir, maps['metallic_roughness'], data=True)
    packed.interpolation = 'Linear'
    packed.extension = 'EXTEND'
    separate = nodes.new('ShaderNodeSeparateColor')
    separate.mode = 'RGB'
    links.new(uv.outputs['UV'], color.inputs['Vector'])
    links.new(uv.outputs['UV'], packed.inputs['Vector'])
    links.new(color.outputs['Color'], bsdf.inputs['Base Color'])
    links.new(packed.outputs['Color'], separate.inputs['Color'])
    links.new(separate.outputs['Green'], bsdf.inputs['Roughness'])
    links.new(separate.outputs['Blue'], bsdf.inputs['Metallic'])
    # Deliberately no imported normal map: it contains the unreadable old glyphs.
    return material


def _rho(points, spec):
    xz = points[..., (0, 2)]
    return np.linalg.norm((xz-np.asarray(spec['center']))/np.asarray(spec['radii']), axis=-1)


def _ring_mask(centers, vertices, spec):
    rho = _rho(centers, spec)
    vertex_rho = _rho(vertices, spec)
    inner, outer = spec['rho']
    low, high = spec['depth']
    selected = (rho >= inner) & (rho <= outer)
    # Existing fine triangles may straddle the mathematical strip edge; guard
    # the lens glass and inner chrome even for these boundary triangles.
    selected &= vertex_rho.min(axis=1) >= inner-.006
    selected &= vertex_rho.max(axis=1) <= outer+.006
    selected &= vertices[:, :, 1].min(axis=1) >= low
    selected &= vertices[:, :, 1].max(axis=1) <= high
    return selected


def _focus_t(points, spec):
    x = points[..., 0]
    top = np.interp(x, spec['x'], spec['top'])
    bottom = np.interp(x, spec['x'], spec['bottom'])
    return (top-points[..., 2])/(top-bottom)


def _project_uv(points, name, specification):
    if name == 'focus':
        x0, x1 = specification['x'][0], specification['x'][-1]
        return np.column_stack(((points[:, 0]-x0)/(x1-x0), 1-_focus_t(points, specification)))
    left, right, bottom, top = specification['bounds']
    return np.column_stack(((points[:, 0]-left)/(right-left), (points[:, 2]-bottom)/(top-bottom)))


def _level_shutter(mesh, coords, triangles, selected):
    """Remove false raised ink inside the planar shutter face, not its boundary."""
    eligible = np.zeros(len(coords), bool)
    eligible[np.unique(triangles[selected])] = True
    eligible[np.unique(triangles[~selected])] = False
    ids = np.flatnonzero(eligible)
    points = coords[ids].astype(np.float64)
    origin = points[:, (0, 2)].mean(axis=0)
    design = np.column_stack((np.ones(len(points)), points[:, (0, 2)]-origin))
    keep = np.abs(points[:, 1]-np.median(points[:, 1])) < .002
    for _ in range(4):
        plane = np.linalg.lstsq(design[keep], points[keep, 1], rcond=None)[0]
        residual = points[:, 1]-design@plane
        keep = np.abs(residual) < max(3*np.median(np.abs(residual)), .0001)
    target = design@plane
    repair = np.abs(points[:, 1]-target) < .004
    eligible[:] = False
    eligible[ids[repair]] = True
    updated = coords.copy()
    updated[ids[repair], 1] = target[repair]
    mesh.vertices.foreach_set('co', updated.ravel())
    mesh.update()
    displacement = np.abs(updated[:, 1]-coords[:, 1])
    report = {'moved_vertices': int(np.count_nonzero(displacement)),
              'maximum_vertex_displacement': float(displacement.max()),
              'scope': 'Depth only, strictly interior shutter-inscription vertices; original boundary retained',
              'outside_coordinates_exact': bool(np.array_equal(updated[~eligible], coords[~eligible])),
              'all_x_z_coordinates_exact': bool(np.array_equal(updated[:, (0, 2)], coords[:, (0, 2)]))}
    return updated, eligible, report


def refine_lower_front(scene, reference_dir):
    """Apply three coherent inscription strips; return measured preservation data."""
    reference_dir = Path(reference_dir)
    specification = json.loads((reference_dir/'lower_front_maps.json').read_text())
    meshes = [obj for obj in scene.objects if obj.type == 'MESH']
    obj = next((item for item in meshes
                if item.name == 'Minolta Autocord | localized reference repairs'),
               max(meshes, key=lambda item: len(item.data.polygons)))
    mesh = obj.data
    if _UV_NAME not in mesh.uv_layers:
        raise ValueError('Run the upper-front pass first to initialize the shared front inscription UVs')
    if any(poly.loop_total != 3 for poly in mesh.polygons):
        raise ValueError('Lower-front masks require the existing triangulated source mesh')
    coords = np.empty(len(mesh.vertices)*3, np.float32)
    mesh.vertices.foreach_get('co', coords)
    coords = coords.reshape(-1, 3)
    matrix = np.asarray(obj.matrix_world, dtype=np.float64)
    world = coords @ matrix[:3, :3].T + matrix[:3, 3]
    indices = np.empty(len(mesh.loops), np.int32)
    mesh.loops.foreach_get('vertex_index', indices)
    triangles = indices.reshape(-1, 3)
    vertices = world[triangles]
    centers = vertices.mean(axis=1)
    old_materials = np.empty(len(mesh.polygons), np.int32)
    mesh.polygons.foreach_get('material_index', old_materials)
    old_uvs = _uv_digests(mesh)
    old_uvs.pop(_UV_NAME)
    old_active_uv = mesh.uv_layers.active_index
    old_render_uv = next((layer.name for layer in mesh.uv_layers if layer.active_render), None)
    objects_before = tuple(item.as_pointer() for item in scene.objects)
    coordinate_digest = _digest(coords)
    topology_digest = _digest(indices)

    controls = np.zeros(len(centers), dtype=bool)
    for cx, cz, radius in _CONTROL_DISKS:
        controls |= (centers[:, 0]-cx)**2+(centers[:, 2]-cz)**2 < radius**2
    masks = {name: _ring_mask(centers, vertices, specification[name])
             for name in ('taking', 'shutter')}
    masks['shutter'] &= vertices[:, :, 2].max(axis=1) < .455
    focus = specification['focus']
    t = _focus_t(centers, focus)
    vertex_t = _focus_t(vertices, focus)
    masks['focus'] = ((centers[:, 0] >= focus['x'][0]) & (centers[:, 0] <= focus['x'][-1]) &
                      (t >= 0) & (t <= 1) & (vertex_t.min(axis=1) >= -.01) &
                      (vertex_t.max(axis=1) <= 1.01) &
                      (vertices[:, :, 1].min(axis=1) >= focus['depth'][0]) &
                      (vertices[:, :, 1].max(axis=1) <= focus['depth'][1]))
    allowed = ~controls & (vertices[:, :, 2].max(axis=1) < .46)
    for name in masks:
        masks[name] &= allowed
        if not masks[name].any():
            raise ValueError(f'No existing physical inscription surface selected for {name}')
    selection_count = sum(mask.astype(np.uint8) for mask in masks.values())
    assert np.all(selection_count <= 1), 'The three physical inscription strips must not overlap'
    selected = selection_count > 0
    # Glass and the substantial bayonet/chrome band are explicit exclusions,
    # not just an after-the-fact claim about small visual changes.
    glass = _rho(centers, specification['taking']) < .79
    radial = np.linalg.norm(centers[:, (0, 2)]-np.array([.013, .311]), axis=1)
    chrome = (radial >= .093) & (radial <= .117) & (centers[:, 1] < -.275)
    assert not np.any(selected & (glass | controls | chrome))
    assert not np.any(selected & (centers[:, 2] >= .46))
    repaired_coords, repaired_vertices, depth_report = _level_shutter(mesh, coords, triangles, masks['shutter'])

    # Share the fourth UV set with the disjoint upper ring: Three.js supports
    # TEXCOORD_0 through TEXCOORD_3, not a fifth independently appended set.
    layer = mesh.uv_layers[_UV_NAME]
    uv = np.empty((len(mesh.loops), 2), np.float32)
    layer.data.foreach_get('uv', uv.ravel())
    assignments = old_materials.copy()
    reports = {}
    for name, mask in masks.items():
        face_ids = np.flatnonzero(mask)
        loop_ids = (face_ids[:, None]*3+np.arange(3)).ravel()
        assert not uv[loop_ids].any(), 'Upper/lower front inscription UV regions must be disjoint'
        uv[loop_ids] = _project_uv(world[indices[loop_ids]], name, specification[name])
        material = _material(reference_dir, name, specification['maps'][name], layer.name)
        mesh.materials.append(material)
        assignments[mask] = len(mesh.materials)-1
        affected_vertices = vertices[mask].reshape(-1, 3)
        reports[name] = {
            'affected_polygons': int(len(face_ids)), 'material': material.name,
            'polygon_ids_sha256': _digest(face_ids),
            'affected_world_bounds': [affected_vertices.min(axis=0).tolist(),
                                      affected_vertices.max(axis=0).tolist()],
            'mask': specification[name], 'maps': specification['maps'][name],
            'map_paths': [str(reference_dir/specification['maps'][name][key])
                          for key in ('basecolor', 'metallic_roughness')],
            'geometry': 'Original strip topology; only the shutter ink surface receives local depth leveling',
        }
    layer.data.foreach_set('uv', uv.ravel())
    mesh.uv_layers.active_index = old_active_uv
    if old_render_uv is not None:
        mesh.uv_layers[old_render_uv].active_render = True
    mesh.polygons.foreach_set('material_index', assignments)
    mesh.update()
    normal_report = inscription_normals(mesh, repaired_coords, indices, {
        name:(np.flatnonzero(mask)[:, None]*3+np.arange(3)).ravel()
        for name, mask in masks.items()
    })

    after_coords = np.empty(coords.size, np.float32)
    mesh.vertices.foreach_get('co', after_coords)
    after_indices = np.empty(indices.size, np.int32)
    mesh.loops.foreach_get('vertex_index', after_indices)
    actual_materials = np.empty(len(mesh.polygons), np.int32)
    mesh.polygons.foreach_get('material_index', actual_materials)
    after_uvs = _uv_digests(mesh)
    checks = {
        'coordinates_outside_shutter_ink_surface_exact': bool(np.array_equal(after_coords.reshape(-1, 3)[~repaired_vertices], coords[~repaired_vertices])),
        'all_x_z_coordinates_exact': bool(np.array_equal(after_coords.reshape(-1, 3)[:, (0, 2)], coords[:, (0, 2)])),
        'all_topology_exact': _digest(after_indices) == topology_digest,
        'all_original_uv_layers_exact': all(after_uvs.get(name) == digest for name, digest in old_uvs.items()),
        'outside_material_assignments_exact': bool(np.array_equal(actual_materials[~selected], old_materials[~selected])),
        'glass_materials_exact': bool(np.array_equal(actual_materials[glass], old_materials[glass])),
        'chrome_bayonet_band_materials_exact': bool(np.array_equal(actual_materials[chrome], old_materials[chrome])),
        'control_materials_exact': bool(np.array_equal(actual_materials[controls], old_materials[controls])),
        'scene_objects_exact': objects_before == tuple(item.as_pointer() for item in scene.objects),
        'all_new_maps_packed': all(node.image.packed_file is not None
                                   for material in mesh.materials if material and material.name.startswith(_PREFIX)
                                   for node in material.node_tree.nodes if node.type == 'TEX_IMAGE'),
    }
    assert all(checks.values()), checks
    obj['lower_front_scope'] = 'Taking/shutter/focus inscriptions; shallow shutter-letter relief leveled, original lens and body shapes retained.'
    return {
        'object': obj.name, 'regions': reports, 'preservation': checks,
        'affected_polygons': int(selected.sum()), 'new_polygons': 0,
        'moved_vertices': depth_report['moved_vertices'],
        'maximum_vertex_displacement': depth_report['maximum_vertex_displacement'],
        'shutter_depth_repair': depth_report,
        'transcription': specification['transcription'],
        'serial_evidence': specification['serial_evidence'],
        'source_references': specification['source_references'],
        'uncertainties': specification['uncertainties'],
        'uv_layer': layer.name, 'original_uv_sha256': old_uvs,
        'original_coordinate_sha256': coordinate_digest, 'original_topology_sha256': topology_digest,
        'material_contract': 'Packed image base color plus glTF metallic/roughness; no procedural shader, imported old normal map or overlay geometry.',
        'normal_handling': 'Smooth fitted inscription-surface corner normals; surrounding normals retained.',
        'surface_normal_repair': normal_report,
        'protected_control_disks_x_z_radius': [list(item) for item in _CONTROL_DISKS],
    }
