import { OfflinePanel } from "./OfflinePanel";
import { exportRolls, importRolls } from '../storage/rollArchive';
import { blockUpdate } from '../offline/client';
import { photoCropPreview } from '../utils/photoFraming';
import { useEffect, useRef, useState } from 'react';
import { FILM_STOCKS, DEFAULT_FILM_STOCK_ID, FilmStockId, getFilmStock } from '../data/filmStocks';
import { EXTRA_FILM_ALLOWANCE, FILM_FORMATS, FilmFormat, FrameSizing, frameAspect, filmLengthUsage, rollFormatLabel } from '../data/filmFormats';
import { RollBundle, RollRepository, StoredRoll, storageMessage } from '../storage/rollRepository';
import { DraftPhoto, processPhotos, releaseDraft } from '../storage/importPhotos';
import { CropInspector } from './CropInspector';
export const rollRepository = new RollRepository();
interface Props { onClose:()=>void;onOpen:(id:string)=>Promise<void>;onExample:()=>void;activeId:string;onRemoved:(id:string)=>void }
type Step='photos'|'details'|'review';
export function RollLibrary({onClose,onOpen,onExample,activeId,onRemoved}:Props) {
  const dialog=useRef<HTMLDialogElement>(null),abort=useRef<AbortController|null>(null),draftRef=useRef<DraftPhoto[]>([]),scroll=useRef(0),returnId=useRef('');
  const [rolls,setRolls]=useState<StoredRoll[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[loading,setLoading]=useState(true);
  const [draft,setDraft]=useState<DraftPhoto[]|null>(null),[editing,setEditing]=useState<StoredRoll|null>(null),[rollId,setRollId]=useState(''),[step,setStep]=useState<Step>('photos'),[selected,setSelected]=useState('');
  const [name,setName]=useState(''),[stock,setStock]=useState<FilmStockId>(DEFAULT_FILM_STOCK_ID),[format,setFormat]=useState<FilmFormat>('135'),[sizing,setSizing]=useState<FrameSizing>('fixed'),[cover,setCover]=useState('');
  const [trash,setTrash]=useState(false),[usage,setUsage]=useState(''),[menu,setMenu]=useState<string|null>(null),[covers,setCovers]=useState<Record<string,{url:string;rotation:number}>>({});
  const [archiveNotice,setArchiveNotice]=useState('');
  useEffect(()=>{blockUpdate('library',true);return()=>blockUpdate('library',false);},[]);
  const backup=(ids:string[])=>void run(async()=>{
    const blob=await exportRolls(rollRepository,ids),url=URL.createObjectURL(blob);
    const link=document.createElement('a');link.href=url;link.download=`darkroom-${new Date().toISOString().slice(0,10)}.darkroom`;link.click();
    setTimeout(()=>URL.revokeObjectURL(url),60000);setMenu(null);setArchiveNotice('Backup prepared. Keep the downloaded .darkroom file for recovery or importing at another address.');
  });
  const restore=(file:File)=>void run(async()=>{const ids=await importRolls(rollRepository,file);await refresh();setArchiveNotice(`Imported ${ids.length} ${ids.length===1?'roll':'rolls'} as separate copies. Existing rolls are unchanged. Rolls from Trash remain in Trash.`);});
  const drag=useRef<number|null>(null);
  const refresh=async()=>{setRolls(await rollRepository.list());const estimate=await navigator.storage?.estimate?.();if(estimate?.usage!==undefined)setUsage(`${(estimate.usage/1048576).toFixed(1)} MB used by this site`);};
  const run=async(fn:()=>Promise<void>)=>{setError('');setBusy(true);try{await fn();}catch(e){setError(storageMessage(e));}finally{setBusy(false);setLoading(false);}};
  useEffect(()=>{const previous=document.activeElement as HTMLElement;dialog.current?.showModal();void run(refresh);return()=>{abort.current?.abort();releaseDraft(draftRef.current);previous?.focus();};},[]);
  useEffect(()=>{let cancelled=false;const urls:string[]=[];void Promise.all(rolls.map(async r=>{try{const c=await rollRepository.thumbnail(r.id,r.coverId),url=URL.createObjectURL(c.blob);urls.push(url);return [r.id,{url,rotation:c.rotation}] as const;}catch{return [r.id,{url:'',rotation:0}] as const;}})).then(entries=>{if(!cancelled)setCovers(Object.fromEntries(entries));else urls.forEach(URL.revokeObjectURL);});return()=>{cancelled=true;urls.forEach(URL.revokeObjectURL);};},[rolls]);
  useEffect(()=>{if(draft!==null){dialog.current?.querySelector<HTMLElement>('[data-step-title]')?.focus();dialog.current?.scrollTo(0,0);}else{dialog.current?.scrollTo(0,scroll.current);if(returnId.current)dialog.current?.querySelector<HTMLButtonElement>(`[data-card-id="${returnId.current}"]`)?.focus({preventScroll:true});}},[step,draft===null]);
  useEffect(()=>{if(menu)dialog.current?.querySelector<HTMLElement>('[role="menuitem"]')?.focus();},[menu]);
  const updateDraft=(photos:DraftPhoto[]|null)=>{draftRef.current=photos??[];setDraft(photos);};
  const reset=()=>{abort.current?.abort();releaseDraft(draftRef.current);updateDraft(null);setEditing(null);setError('');setProgress('');};
  const start=()=>{if(!crypto.subtle||!crypto.randomUUID){setError('Photo import needs a secure connection. Open the HTTPS preview address and try again.');return;}scroll.current=dialog.current?.scrollTop??0;returnId.current='';reset();setRollId(crypto.randomUUID());setName('');setStock(DEFAULT_FILM_STOCK_ID);setFormat('135');setSizing('fixed');setCover('');setSelected('');setStep('photos');updateDraft([]);};
  const choose=(files:File[])=>void run(async()=>{
    abort.current=new AbortController();const controller=abort.current,prior=draftRef.current;setProgress('Processing photographs…');
    try{const photos=await processPhotos(files,rollId,controller.signal,(done,total)=>setProgress(`Processed ${done} / ${total}`),prior);controller.signal.throwIfAborted();updateDraft([...prior,...photos]);if(!cover)setCover(photos.find(p=>p.frame)?.id??'');if(!selected)setSelected(photos[0]?.id??'');}
    catch(e){if(!controller.signal.aborted)throw e;setProgress('Processing cancelled. Your earlier photographs are retained.');}
  });
  const edit=(id:string)=>void run(async()=>{scroll.current=dialog.current?.scrollTop??0;returnId.current=id;setMenu(null);const b=await rollRepository.read(id);setEditing(b.roll);setRollId(id);setName(b.roll.name);setStock(b.roll.stockId);setFormat(b.roll.format);setSizing(b.roll.sizing??'fixed');setCover(b.roll.coverId);setSelected(b.frames[0]?.id??'');setStep('details');updateDraft(b.roll.frameIds.map(id=>{const frame=b.frames.find(f=>f.id===id)!;return {id,filename:frame.filename,frame,blobs:[],duplicate:false,keepDuplicate:true,preview:URL.createObjectURL(b.blobs.find(x=>x.key===frame.thumbnailKey)!.blob),reviewPreview:URL.createObjectURL(b.blobs.find(x=>x.key===frame.viewingKey)!.blob)};}));});
  const move=(from:number,to:number)=>{if(!draft||to<0||to>=draft.length)return;const next=[...draft], [p]=next.splice(from,1);next.splice(to,0,p);updateDraft(next);};
  const length=filmLengthUsage(format,sizing,draft?.flatMap(p=>p.frame?[p.frame]:[])??[]);
  const valid=!!draft?.length&&!draft.some(p=>!p.frame||p.duplicate&&!p.keepDuplicate);
  const save=()=>void run(async()=>{
    if(!valid||!draft)throw new Error('Resolve failed files and duplicates before saving.');
    const frames=draft.map(p=>p.frame!),ids=frames.map(f=>f.id),now=Date.now();
    const roll:StoredRoll={id:rollId,name,stockId:stock,format,sizing,frameIds:ids,coverId:ids.includes(cover)?cover:ids[0],createdAt:editing?.createdAt??now,updatedAt:now,trashedAt:null,view:editing?.view?{...editing.view,zoom:NaN,overview:null}:undefined};
    const bundle:RollBundle={roll,frames,blobs:draft.flatMap(p=>p.blobs)};abort.current=new AbortController();setProgress('Saving roll…');await rollRepository.save(bundle,abort.current.signal);setProgress('Refreshing library…');void navigator.storage?.persist?.().catch(()=>false);await refresh();setProgress('Opening photographs…');await onOpen(rollId);reset();onClose();
  });
  const removePhoto=(id:string)=>{const i=draft!.findIndex(p=>p.id===id);releaseDraft([draft![i]]);const next=draft!.filter(p=>p.id!==id);updateDraft(next);if(cover===id)setCover(next.find(p=>p.frame)?.id??'');if(selected===id)setSelected(next[Math.min(i,next.length-1)]?.id??'');};
  const closeMenu=()=>{const id=menu;setMenu(null);dialog.current?.querySelector<HTMLElement>(`[data-menu-id="${id}"]`)?.focus();};
  const visible=rolls.filter(r=>trash?r.trashedAt!==null:r.trashedAt===null),active=draft?.find(p=>p.id===selected)??draft?.[0],index=draft?.findIndex(p=>p.id===active?.id)??0;
  const go=(next:Step)=>{setError('');setStep(next);};
  return <dialog ref={dialog} className="library-dialog" aria-label={draft?'Review roll':'Roll library'} onCancel={e=>{e.preventDefault();if(menu)closeMenu();else if(busy)abort.current?.abort();else if(draft)reset();else onClose();}} onKeyDown={e=>e.stopPropagation()}>
    <header><div><p className="library-eyebrow">YOUR DARKROOM</p><h1>{draft?editing?'Edit roll':'New roll':trash?'Trash':'Your rolls'}</h1></div><div className="library-header-actions">{draft===null&&!trash&&<button className="primary" disabled={busy} onClick={start}>New roll</button>}<button onClick={()=>busy?abort.current?.abort():onClose()}>{busy?'Cancel processing':'Close'}</button></div></header>
    {error&&<p role="alert" className="library-error">{error} <button disabled={busy} onClick={()=>void run(refresh)}>Retry storage</button></p>}
    {progress&&draft&&(step==='photos'||busy)&&<p role="status">{progress}</p>}
    {draft?.some(p=>p.notice)&&<p role="status">{draft.filter(p=>p.notice).map(p=>`${p.filename}: ${p.notice}`).join(' ')}</p>}
    {draft===null?<>
      <div className="archive-actions"><button disabled={busy||!rolls.length} onClick={()=>backup(rolls.map(r=>r.id))}>Export all rolls</button><label>Import backup<input aria-label="Import backup" type="file" accept=".darkroom,application/vnd.darkroom.rolls" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)restore(file);e.target.value='';}}/></label></div>
      <p>Backups include originals, edits and saved views, including Trash. Importing always creates separate copies. Up to 512 MB per backup; use a roll’s Actions menu for individual exports.</p>
      {archiveNotice&&<p role="status">{archiveNotice}</p>}
      <div className="library-toolbar"><p>{trash?'Removed rolls can always be restored.':`${visible.length} ${visible.length===1?'roll':'rolls'} in your archive`}</p><button disabled={busy} onClick={()=>setTrash(!trash)}>{trash?'Back to rolls':'Trash'}</button><button disabled={busy} onClick={()=>{onExample();onClose();}}>Open built-in example</button></div>
      {loading?<p role="status" className="library-empty">Opening your archive…</p>:!visible.length&&<div className="library-empty"><h2>{trash?'Nothing in Trash':'A home for your photographs'}</h2><p>{trash?'Removed rolls stay here until you restore them.':'Bring your scans to the light table. Start with a few photographs or an entire roll.'}</p></div>}
      <div className="library-cards">{visible.map(r=><article key={r.id} data-roll-id={r.id}>
        <button data-card-id={r.id} className="roll-card-open" disabled={busy||trash} aria-label={`Open ${r.name}`} onClick={()=>void run(async()=>{await onOpen(r.id);onClose();})}>
          <div className="roll-cover">{covers[r.id]?.url?<img style={{transform:`rotate(${covers[r.id].rotation}deg)`,maxWidth:covers[r.id].rotation%180?'150px':undefined}} src={covers[r.id].url} alt={`Cover of ${r.name}`}/>:<span>Cover unavailable</span>}</div><h2>{r.name}</h2><p>{rollFormatLabel(r.format,r.sizing)} · {r.frameIds.length} frames</p><p>{getFilmStock(r.stockId).displayName}</p>
        </button>
        <div className="roll-card-footer">{activeId===r.id?<span className="current-roll">Currently open</span>:<span/>}{trash?<button disabled={busy} onClick={()=>void run(async()=>{await rollRepository.trash(r.id,false);await refresh();})}>Restore {r.name}</button>:<button data-menu-id={r.id} aria-label={`Actions for ${r.name}`} aria-haspopup="menu" aria-expanded={menu===r.id} disabled={busy} onClick={()=>setMenu(menu===r.id?null:r.id)}>•••</button>}</div>
        {menu===r.id&&<div role="menu" className="roll-menu" aria-label={`Actions for ${r.name}`} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();closeMenu();}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();const items=Array.from(e.currentTarget.querySelectorAll<HTMLElement>('[role="menuitem"]'));items[(items.indexOf(document.activeElement as HTMLElement)+(e.key==='ArrowDown'?1:items.length-1))%items.length]?.focus();}if(e.key==='Tab')setMenu(null);}}><button role="menuitem" onClick={()=>backup([r.id])}>Export {r.name}</button><button role="menuitem" onClick={()=>edit(r.id)}>Edit {r.name}</button><button role="menuitem" onClick={()=>void run(async()=>{setMenu(null);await rollRepository.trash(r.id);onRemoved(r.id);await refresh();})}>Move {r.name} to Trash</button></div>}
      </article>)}</div>
      <footer className="storage-footer"><details><summary>Stored in this browser{usage?` · ${usage}`:''}</summary><p>Clearing site data removes your rolls. Export backups before changing the protocol, hostname or port; each address has a separate library. Keep the old library until you verify your imported copies. Photographs stay on this device and are never uploaded.</p></details><OfflinePanel /></footer>
    </>:<>
      <nav className="import-steps" aria-label="Import progress">{(['photos','details','review'] as Step[]).filter(s=>!editing||s!=='photos').map((s,i)=><button key={s} aria-label={s==='photos'?'Photographs':s==='details'?'Roll details':'Review'} aria-current={step===s?'step':undefined} disabled={busy||(s!=='photos'&&!draft.length)||(s==='review'&&!name.trim())} onClick={()=>go(s)}><span>{i+1}</span>{s==='photos'?'Photographs':s==='details'?'Roll details':'Review'}</button>)}</nav>
      <h2 tabIndex={-1} data-step-title>{step==='photos'?'Choose your photographs':step==='details'?'Give this roll an identity':'Review every frame'}</h2>
      {step==='photos'&&<>
        <div className="photo-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy)choose(Array.from(e.dataTransfer.files));}}><h3>{draft.length?'Add to this roll':'Bring your scans into the darkroom'}</h3><p>Drop JPEG or PNG positive scans here</p><label className="choose-photos">{draft.length?'Add photographs':'Choose photographs'}<input aria-label="Choose photographs" type="file" accept="image/jpeg,image/png" multiple disabled={busy} onChange={e=>{choose(Array.from(e.target.files??[]));e.target.value='';}}/></label></div>
        <p>{draft.length} photographs selected · Your order and edits are retained when adding another batch.</p><details><summary>Supported files and limits</summary><p>JPEG/PNG positive scans. Up to 300 MB per draft. Roll capacity depends on image width and film length; 40 MB and 40 megapixels per file. Partial rolls are welcome.</p></details>
        {!!draft.length&&<div className="import-filmline">{draft.map(p=><div key={p.id}>{p.preview&&<img src={p.preview} alt={p.filename}/>}<span>{p.filename}</span>{p.error&&<span role="alert">{p.error}</span>}{p.duplicate&&<span>Duplicate — resolve in Review</span>}</div>)}</div>}
      </>}
      {step==='details'&&<><div className="library-details"><label>Roll name<input maxLength={120} value={name} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="e.g. Summer on the coast"/></label>
        <fieldset disabled={busy}><legend>Film type</legend><label><input type="radio" name="film-type" checked={format==='135'} onChange={()=>{setFormat('135');setSizing('fixed');}}/>35mm</label><label><input type="radio" name="film-type" checked={format!=='135'} onChange={()=>{setFormat('66');setSizing('free');}}/>120</label></fieldset>
        <label>Frame size (optional)<select aria-label="Film format" value={sizing==='free'?'free':format} disabled={busy} onChange={e=>{if(e.target.value==='free')setSizing('free');else{setFormat(e.target.value as FilmFormat);setSizing('fixed');}}}>{(format==='135'?['135']:['645','66','67','69']).map(id=><option key={id} value={id}>{FILM_FORMATS[id as FilmFormat].label}</option>)}<option value="free">Free · keep original proportions</option></select><small>{sizing==='free'?'All photographs keep their full composition at the same height. Width varies with each photograph.':'Photographs fill the selected frame size. Adjust cropping in Review.'}</small></label>
        <label>Film stock<select aria-label="Film stock" value={stock} disabled={busy} onChange={e=>setStock(e.target.value as FilmStockId)}>{FILM_STOCKS.map(s=><option key={s.id} value={s.id}>{s.displayName}</option>)}</select></label></div><div className="live-roll-label"><span>{rollFormatLabel(format,sizing)} / {getFilmStock(stock).displayName}</span><h3>{name||'Untitled roll'}</h3><p>{draft.length} photographs</p></div></>}
      {step==='review'&&<><p className="review-summary">{name} · {rollFormatLabel(format,sizing)} · {draft.length} photographs</p><div className="review-layout"><div><ol className="draft-photos">{draft.map((p,i)=><li key={p.id} draggable={!busy} onDragStart={()=>{drag.current=i;setSelected(p.id);}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(drag.current!==null)move(drag.current,i);drag.current=null;}}><button aria-label={`Select frame ${i+1}`} aria-pressed={active?.id===p.id} onClick={()=>setSelected(p.id)}><div className="draft-preview" style={{aspectRatio:frameAspect(format,sizing,p.frame),width:`min(100%, ${190*frameAspect(format,sizing,p.frame)}px)`}}>{p.preview&&<img src={p.preview} alt={p.filename} style={photoCropPreview(p.frame?p.frame.width/p.frame.height:1,frameAspect(format,sizing,p.frame),p.frame?.rotation??0,p.frame?.cropPosition)}/>}</div><strong>Frame {i+1}{cover===p.id?' · Cover':''}</strong><span>{p.filename}</span>{p.error&&<span className="photo-issue">Cannot read file</span>}{p.duplicate&&!p.keepDuplicate&&<span className="photo-issue">Duplicate</span>}</button></li>)}</ol></div>
        {active&&<div className="selected-review"><CropInspector key={active.id} photo={active} format={format} sizing={sizing} disabled={busy} onChange={cropPosition=>updateDraft(draft.map(p=>p.id===active.id?{...p,frame:{...p.frame!,cropPosition}}:p))}/><h3>Frame {index+1} · {active.filename}</h3>{active.error&&<p role="alert">{active.error}</p>}{active.duplicate&&<label><input type="checkbox" checked={active.keepDuplicate} disabled={busy} onChange={e=>updateDraft(draft.map(p=>p.id===active.id?{...p,keepDuplicate:e.target.checked}:p))}/>Keep this duplicate content</label>}<div className="draft-actions"><button disabled={busy||index===0} aria-label={`Move frame ${index+1} earlier`} onClick={()=>move(index,index-1)}>Earlier</button><button disabled={busy||index===draft.length-1} aria-label={`Move frame ${index+1} later`} onClick={()=>move(index,index+1)}>Later</button><button disabled={busy||!active.frame} aria-label={`Rotate frame ${index+1}`} onClick={()=>updateDraft(draft.map(p=>p.id===active.id?{...p,frame:{...p.frame!,rotation:(p.frame!.rotation+90)%360,cropPosition:p.frame!.cropPosition?{x:-p.frame!.cropPosition.y,y:p.frame!.cropPosition.x}:undefined}}:p))}>Rotate 90°</button><button disabled={busy||!active.frame} aria-pressed={cover===active.id} onClick={()=>setCover(active.id)}>Cover</button><button disabled={busy} onClick={()=>removePhoto(active.id)}>Remove {active.filename}</button></div></div>}
      </div>{!valid&&<p role="status">Select flagged photographs to resolve issues before saving.</p>}</>}

      <footer className="import-footer">
      <div className={`film-length ${length.exceeded?'is-overfull':''}`} aria-label="Film length">
        <div><strong>Film length</strong><span>{Math.ceil(length.used)} / {length.capacity} mm</span></div>
        <progress aria-label="Film length used" max={length.capacity} value={Math.min(length.used,length.capacity)}/>
        <p role="status">{length.exceeded?`${Math.ceil(length.used-length.capacity)} mm over capacity. Remove photographs in Review or choose another frame size.`:length.usingExtra?`Using extra allowance beyond the usual ${length.nominal} mm · ${Math.floor(length.remaining)} mm remaining. You can save this roll.`:`${Math.floor(length.remaining)} mm remaining · Includes ${EXTRA_FILM_ALLOWANCE*100}% extra length for special cases. Frame spacing is included.`}</p>
      </div>
      <div className="import-footer-actions"><button onClick={()=>busy?abort.current?.abort():reset()}>{busy?'Cancel processing':editing?'Cancel edits':'Cancel draft'}</button><div>{step!=='photos'&&!(editing&&step==='details')&&<button disabled={busy} onClick={()=>go(step==='review'?'details':'photos')}>Back</button>}{step==='photos'?<button className="primary" disabled={busy||!draft.length} onClick={()=>go('details')}>Continue to roll details</button>:step==='details'?<button className="primary" disabled={busy||!name.trim()||!draft.length} onClick={()=>go('review')}>Review photographs</button>:<button className="primary" disabled={busy||!name.trim()||!valid||length.exceeded} onClick={save}>Save and open</button>}</div></div></footer>
    </>}
  </dialog>;
}
