import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Regenerates src/data/showreelRolls.json from public/assets/photos/showreel/:
// one roll per subfolder named `<order>_<format>_<stock>` (for example
// `4_66_gold200`; half frame is `35half` or `35_half`), its JPEGs (sRGB) in filename order. Roll names already in the
// manifest are kept. Run `npm run showreel:manifest` after changing the folder.
const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.join(repo, 'src/data/showreelRolls.json');
const SHOWREEL_PHOTO_PATH = '/assets/photos/showreel/';
const root = path.join(repo, 'public', SHOWREEL_PHOTO_PATH);

const FORMATS: Record<string, { format: string; sizing: 'fixed' | 'free'; gate: number }> = {
  '35': { format: '135', sizing: 'fixed', gate: 36 / 24 },
  '35wide': { format: '135', sizing: 'free', gate: 0 },
  '35half': { format: '135-half', sizing: 'fixed', gate: 18 / 24 },
  '645': { format: '645', sizing: 'fixed', gate: 41.5 / 56 },
  '66': { format: '66', sizing: 'fixed', gate: 1 },
  '67': { format: '67', sizing: 'fixed', gate: 68.5 / 56 },
  '69': { format: '69', sizing: 'fixed', gate: 82.6 / 56 },
};
const STOCKS: Record<string, string> = {
  fuji200: 'fuji-200', proimage100: 'pro-image-100', gold200: 'gold-200', ultramax400: 'ultramax-400',
  e100: 'ektachrome-e100', ektar100: 'ektar-100', portra160: 'portra-160', portra400: 'portra-400', portra800: 'portra-800',
  rdp: 'provia-100', provia100: 'provia-100', rvp50: 'velvia-50', velvia50: 'velvia-50', rvp100: 'velvia-100', velvia100: 'velvia-100',
};

/** Pixel size from a JPEG's start-of-frame marker. */
function jpegSize(file: string) {
  const bytes = fs.readFileSync(file);
  for (let i = 2; i + 9 < bytes.length;) {
    if (bytes[i] !== 0xff) { i++; continue; }
    const marker = bytes[i + 1], length = bytes.readUInt16BE(i + 2);
    if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) return { width: bytes.readUInt16BE(i + 7), height: bytes.readUInt16BE(i + 5) };
    i += 2 + length;
  }
  throw new Error(`No JPEG frame header in ${file}`);
}

if (!fs.existsSync(root)) throw new Error(`Showreel photographs not found at ${root}`);
const previous = fs.existsSync(output) ? JSON.parse(fs.readFileSync(output, 'utf8')) : { rolls: [] };
const rolls = fs.readdirSync(root, { withFileTypes: true }).filter(entry => entry.isDirectory()).map(entry => entry.name).sort().map(folder => {
  const match = folder.match(/^(\d+)_([a-z0-9]+(?:_half)?)_([a-z0-9]+)$/i);
  const size = match && FORMATS[match[2].toLowerCase().replace('_', '')], stockId = match && STOCKS[match[3].toLowerCase()];
  if (!size || !stockId) throw new Error(`Unrecognized roll folder ${folder}: expected <order>_<${Object.keys(FORMATS).join('|')}>_<${Object.keys(STOCKS).join('|')}>`);
  const files = fs.readdirSync(path.join(root, folder)).filter(name => /\.jpe?g$/i.test(name)).sort();
  if (!files.length) throw new Error(`No photographs in ${folder}`);
  const id = `showreel-${folder.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`;
  const name = previous.rolls.find((roll: { folder: string }) => roll.folder === folder)?.name ?? folder;
  return {
    id, folder, name, stockId, format: size.format, sizing: size.sizing,
    frames: files.map(file => {
      const { width, height } = jpegSize(path.join(root, folder, file)), aspect = width / height;
      // Placed like the importer: a vertical shot lies across a landscape gate, and along a free frame.
      const turned = size.sizing === 'free' ? aspect < 1 : Math.min(1 / aspect / size.gate, size.gate * aspect) > Math.min(aspect / size.gate, size.gate / aspect) + 1e-9;
      return { id: `${id}-${path.parse(file).name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`, src: `${SHOWREEL_PHOTO_PATH}${folder}/${file}`, width, height, rotation: turned ? 90 : 0 };
    }),
  };
});
const manifest = {
  note: 'Generated by `npm run showreel:manifest` from public/assets/photos/showreel/. Roll names may be edited; they are kept on regeneration.',
  rolls,
};
fs.writeFileSync(output, JSON.stringify(manifest, null, 2) + '\n');
console.log(`Wrote ${rolls.length} rolls, ${rolls.reduce((sum, roll) => sum + roll.frames.length, 0)} photographs from ${root}`);
